/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */


#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

static const ResourceVersion SYSTEM_RESOURCE_VERSION = {
  .crc = 2065217901,  // 0x7b18b96d - content CRC  // 0x59ab6e87 - patched timezone DB
  .timestamp = 0
};
